import React, { useState } from 'react';
import { predictCandidate } from '../services/predictionService';

const initialFormState = {
  candidateName: '',
  age: '',
  gender: '',
  degree: '',
  branch: '',
  collegeTier: '',
  cgpa: '',
  programmingLanguages: '',
  skillsCount: '',
  projectsCount: '',
  internshipCount: '',
  certificationCount: '',
  hackathonCount: '',
  codingScore: '',
  communicationScore: '',
  leadershipScore: '',
  experienceYears: ''
};

export default function PredictionPage() {
  const [form, setForm] = useState(initialFormState);
  const [result, setResult] = useState({
    prediction: 'Shortlisted',
    probability: 0.93,
    reasons: ['Excellent Coding Score', 'Multiple Projects', 'Strong Internship Profile']
  });
  const [loading, setLoading] = useState(false);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
  };

  const handlePredict = async (event) => {
    event.preventDefault();
    setLoading(true);

    try {
      const response = await predictCandidate(form);
      setResult(response.data);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="grid gap-6 xl:grid-cols-[0.95fr_1.05fr]">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-xl shadow-cyan-950/10">
        <p className="text-xs uppercase tracking-[0.3em] text-cyan-300">Prediction Input</p>
        <h1 className="mt-2 text-3xl font-semibold">Generate shortlist prediction</h1>
        <p className="mt-3 text-sm leading-6 text-slate-300">
          Send structured candidate features to the backend and receive probability, model output, and feature importance.
        </p>

        <form onSubmit={handlePredict} className="mt-6 grid gap-4 sm:grid-cols-2">
          {Object.entries(form).map(([key, value]) => (
            <label key={key} className="block">
              <span className="mb-2 block text-sm text-slate-300">{key}</span>
              <input
                name={key}
                value={value}
                onChange={handleChange}
                className="w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm outline-none"
                placeholder={key}
              />
            </label>
          ))}
          <button
            type="submit"
            disabled={loading}
            className="mt-2 rounded-2xl bg-cyan-400 px-6 py-3 text-sm font-semibold text-slate-950 disabled:opacity-70"
          >
            {loading ? 'Predicting...' : 'Predict Shortlist'}
          </button>
        </form>
      </section>

      <section className="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-xl shadow-cyan-950/10">
        <p className="text-xs uppercase tracking-[0.3em] text-cyan-300">Prediction Result</p>
        <div className="mt-4 rounded-[1.75rem] border border-cyan-400/20 bg-slate-950/70 p-6">
          <div className="flex items-center justify-between gap-4">
            <h2 className="text-2xl font-semibold">{result.prediction || 'Shortlisted'}</h2>
            <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-medium text-emerald-300">
              Probability {Math.round((result.probability || 0) * 100)}%
            </span>
          </div>
          <p className="mt-4 text-sm leading-6 text-slate-300">
            Reasons are derived from feature importance scores generated by the selected classical ML model.
          </p>
          <ul className="mt-6 space-y-3 text-sm text-slate-200">
            {(result.reasons || []).map((reason) => (
              <li key={reason} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
                {reason}
              </li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
}
